import Vue from 'vue'
import { Button, Icon, NavBar, Form, Field, Toast, Tabbar, TabbarItem, Image as VanImage, Grid, GridItem, cell, CellGroup, Dialog, popup, Notify, DatetimePicker } from 'vant'

Vue.use(Button)
Vue.use(Icon)
Vue.use(NavBar)
Vue.use(Form)
Vue.use(Field)
Vue.use(Toast)
Vue.use(Tabbar)
Vue.use(TabbarItem)
Vue.use(VanImage)
Vue.use(Grid)
Vue.use(GridItem)
Vue.use(cell)
Vue.use(CellGroup)
Vue.use(Dialog)
Vue.use(popup)
Vue.use(Notify)
Vue.use(DatetimePicker)
